#!/system/bin/sh

# Menyimpan perintah dari argumen pertama
cmd="$1"

# Set variabel-variabel umum
export bin="/system/bin"
export PATH="/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export TERM="linux"
export HOME="/root"
export USER="root"
export LOGNAME="root"
unset LD_PRELOAD
unset PROMPT_COMMAND
localbuild="/data/local/tmp/ubuntu"

# Fungsi untuk menghapus Ubuntu
uninstall() {
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m MENGHAPUS UBUNTU... \e[0m"
  sudo rm -rf "$localbuild" 2> /dev/null
  if [ -d "$localbuild" ]; then
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m RESTART PERANGKAT DAN COBA LAGI! \e[0m"
  else
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PENGHAPUSAN SELESAI! \e[0m"
    rm "$PREFIX/bin/ubuntu" 2> /dev/null
    rmdir "$localbuild" 2> /dev/null
  fi
  exit
}

# Jalankan perintah jika pengguna bukan root
if [ "$EUID" -ne 0 ]; then
  case "$cmd" in
    "" | "-u" | "--uninstall")
      uninstall
      ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PERINTAH TIDAK VALID! \e[0m"
      exit
      ;;
  esac

  # Setting beberapa perintah dan mount poin
  setenforce 0
  mountpoint -q "$localbuild/dev" 2> /dev/null
  mount -o bind /dev "$localbuild/dev" 2> /dev/null
  mount -t devpts devpts "$localbuild/dev/pts" 2> /dev/null
  mount -t proc proc "$localbuild/proc" 2> /dev/null
  mount -t sysfs sysfs "$localbuild/sys" 2> /dev/null
  mount -t tmpfs none "$localbuild/tmp" 2> /dev/null

  clear
  chroot "$localbuild" /bin/login -f root
else
  case "$cmd" in
    "" | "-u" | "--uninstall")
      uninstall
      ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PERINTAH TIDAK VALID! \e[0m"
      exit
      ;;
  esac

  # Setting beberapa perintah dan mount poin dengan sudo
  sudo setenforce 0
  sudo mount -o remount,suid /data 2> /dev/null
  sudo mountpoint -q "$localbuild/dev" 2> /dev/null
  sudo mount -o bind /dev "$localbuild/dev" 2> /dev/null
  sudo mount -t devpts devpts "$localbuild/dev/pts" 2> /dev/null
  sudo mount -t proc proc "$localbuild/proc" 2> /dev/null
  sudo mount -t sysfs sysfs "$localbuild/sys" 2> /dev/null
  sudo mount -t tmpfs none "$localbuild/tmp" 2> /dev/null

  clear
  sudo chroot "$localbuild" /bin/login -f root
fi
