#!/system/bin/sh

cmd=$1
export bin=/system/bin
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD
#!/system/bin/sh

localbuild="/data/local/tmp/ubuntu"

# Fungsi untuk menghapus Ubuntu
uninstall() {
  if [ -d "$localbuild" ]; then
    echo "Menghapus Ubuntu..."
    if sudo umount -l $localbuild/dev 2>/dev/null && \
       sudo umount -l $localbuild/dev/pts 2>/dev/null && \
       sudo umount -l $localbuild/proc 2>/dev/null && \
       sudo umount -l $localbuild/sys 2>/dev/null && \
       sudo umount -l $localbuild/tmp 2>/dev/null; then
      sudo rm -rf $localbuild
      rm $PREFIX/bin/ubuntu 2>/dev/null
      echo "Penghapusan selesai!"
    else
      echo "Gagal menghapus Ubuntu."
    fi
  else
    rm $PREFIX/bin/ubuntu 2>/dev/null
    echo "Tidak ada instalasi Ubuntu yang ditemukan."
  fi
}

# Periksa izin root
if [ "$EUID" -ne 0 ]; then
  echo "Perintah ini memerlukan akses root."
  exit 1
fi

# Periksa argumen
case "$1" in
  "")
    uninstall
    ;;
  "-u" | "--uninstall")
    uninstall
    ;;
  *)
    echo "Perintah tidak valid. Gunakan -u atau --uninstall untuk menghapus Ubuntu."
    exit 1
    ;;
esac

exit 0
