#!/system/bin/sh

# Menyimpan perintah dari argumen pertama
cmd="$1"

# Set variabel-variabel umum
export bin="/system/bin"
export PATH="/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export TERM="linux"
export HOME="/root"
export USER="root"
export LOGNAME="root"
unset LD_PRELOAD
unset PROMPT_COMMAND
localbuild="/data/local/tmp/ubuntu"

# Fungsi untuk menghapus instalasi Ubuntu
uninstall() {
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m MENGHAPUS UBUNTU... \e[0m"
  
  # Hapus direktori instalasi Ubuntu
  sudo rm -rf $localbuild 2> /dev/null

  # Periksa apakah direktori masih ada
  if [ -d "$localbuild" ]; then
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m GAGAL MENGHAPUS! \e[0m"
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m RESTART PERANGKAT DAN COBA LAGI! \e[0m"
  else
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PENGHAPUSAN SELESAI! \e[0m"
    
    # Hapus symlink jika ada
    sudo rm $PREFIX/bin/ubuntu 2> /dev/null

    # Hapus direktori localbuild jika kosong
    sudo rmdir $localbuild 2> /dev/null
  fi
  exit
}

# Periksa izin superuser
if [ "$EUID" -ne 0 ]; then
  case $cmd in
    "")
      # Tidak ada perintah, lanjutkan
      ;;
    "-u" | "--uninstall")
      uninstall
      ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PERINTAH TIDAK VALID! \e[0m"
      exit
      ;;
  esac

  # Izinkan mode penegakan selinux
  setenforce 0
  
  # Mount direktori yang diperlukan ke dalam chroot
  mountpoint -q $localbuild/dev 2> /dev/null
  mount -o bind /dev $localbuild/dev 2> /dev/null
  mount -t devpts devpts $localbuild/dev/pts 2> /dev/null
  mount -t proc proc $localbuild/proc 2> /dev/null
  mount -t sysfs sysfs $localbuild/sys 2> /dev/null
  mount -t tmpfs none $localbuild/tmp 2> /dev/null

  clear
  chroot $localbuild /bin/login -f root
else
  case $cmd in
    "")
      # Tidak ada perintah, lanjutkan
      ;;
    "-u" | "--uninstall")
      uninstall
      ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m PERINTAH TIDAK VALID! \e[0m"
      exit
      ;;
  esac

  # Izinkan mode penegakan selinux
  sudo setenforce 0
  
  # Izinkan suid di /data
  sudo mount -o remount,suid /data 2> /dev/null

  # Mount direktori yang diperlukan ke dalam chroot
  sudo mountpoint -q $localbuild/dev 2> /dev/null
  sudo mount -o bind /dev $localbuild/dev 2> /dev/null
  sudo mount -t devpts devpts $localbuild/dev/pts 2> /dev/null
  sudo mount -t proc proc $localbuild/proc 2> /dev/null
  sudo mount -t sysfs sysfs $localbuild/sys 2> /dev/null
  sudo mount -t tmpfs none $localbuild/tmp 2> /dev/null

  clear
  sudo chroot $localbuild /bin/login -f root
fi
